name: Dependabot Enable auto-merge

permissions: { }
on:
  pull_request:
    branches:
      - 'main'

jobs:
  
  ApproveDependabotPr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: cache-restore-nuget-packages
        id: cache-restore-nuget-packages
        uses: actions/cache/restore@v4
        with:
          path: |
            '${{ github.workspace }}/.nuget-packages'
          key: nuget-packages
      
      - name: ApproveDependabotPr
        id: ApproveDependabotPr
        run: dotnet run --project _atom/_atom.csproj ApproveDependabotPr --skip --headless
        env:
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          azure-vault-address: ${{ vars.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ vars.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ vars.AZURE_VAULT_APP_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.number }}
          NUGET_PACKAGES: '${{ github.workspace }}/.nuget-packages'
      
      - name: cache-save-nuget-packages
        id: cache-save-nuget-packages
        uses: actions/cache/save@v4
        if: steps.cache-restore-nuget-packages.outputs.cache-hit != true
        with:
          path: |
            '${{ github.workspace }}/.nuget-packages'
          key: nuget-packages
